// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Only log in development mode
if (import.meta.env.DEV) {
  console.log("Supabase URL:", import.meta.env.VITE_SUPABASE_URL ? "SET" : "MISSING");
  console.log("Supabase Key:", import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? "SET" : "MISSING");
}

// Remove quotes if present in env variables and trim whitespace
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || '').replace(/^["']|["']$/g, '').trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '').replace(/^["']|["']$/g, '').trim();

// Store configuration error for graceful handling
let configError: Error | null = null;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Log error only in development mode to avoid exposing config details
  if (import.meta.env.DEV) {
    console.error('Supabase Configuration Error: Missing environment variables');
  }
  configError = new Error(
    'Missing Supabase environment variables. Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in your .env file.'
  );
} else {
  // Validate URL format
  if (!SUPABASE_URL.startsWith('http://') && !SUPABASE_URL.startsWith('https://')) {
    if (import.meta.env.DEV) {
      console.error('Invalid Supabase URL format');
    }
    configError = new Error('Invalid Supabase URL format. URL must start with http:// or https://');
  } else if (import.meta.env.DEV) {
    // Log minimal configuration info only in development
    console.log('✅ Supabase Client Initialized');
  }
}

// Create a dummy client if config is invalid to prevent app crash
// Components should check supabaseError before using supabase
const DUMMY_URL = 'https://placeholder.supabase.co';
const DUMMY_KEY = 'placeholder-key';

// Import the supabase client like this:
// import { supabase, supabaseError } from "@/integrations/supabase/client";

export const supabaseError = configError;

export const supabase = configError 
  ? createClient<Database>(DUMMY_URL, DUMMY_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  // Remove custom fetch override to ensure Supabase client properly handles headers
  // The Supabase client automatically adds 'apikey' and 'Authorization' headers
});